version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - ls
      - echo $TAGG
      - echo $IMAGE_REPO_NAME
      - echo Build started on `date`
      - echo $PASSW
      - docker login --username=veda1729 --password $PASSW
      - echo Building the Docker image...          
      - docker build --tag $IMAGE_REPO_NAME:$TAGG .
      - docker tag $IMAGE_REPO_NAME:$TAGG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAGG     
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$TAGG
      - printf '[{"name":"webapp","imageUri":"%s"}]' $IMAGE_REPO_NAME:$TAGG > imagedefinitions.json
artifacts:
    files: imagedefinitions.json
